/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuthenticatedResponse {
  'message' : string,
  'timestamp' : Time,
}
export interface Blob { 'content' : Blob }
export interface Comment {
  'id' : bigint,
  'commenter' : Principal,
  'text' : string,
  'timestamp' : Time,
}
export interface DirectMessage {
  'id' : DirectMessageId,
  'text' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export type DirectMessageId = bigint;
export type ExternalBlob = Uint8Array;
export interface Notification {
  'id' : bigint,
  'recipient' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export interface Post {
  'id' : PostId,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : Time,
  'image' : [] | [Blob],
  'comments' : Array<Comment>,
}
export type PostId = bigint;
export interface StatusUpdate {
  'id' : StatusUpdateId,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type StatusUpdateId = bigint;
export interface Story {
  'id' : StoryId,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type StoryId = bigint;
export type Time = bigint;
export interface UserProfile {
  'id' : UserProfileId,
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'followers' : Array<UserProfileId>,
  'following' : Array<UserProfileId>,
  'followPrice' : bigint,
  'principalId' : Principal,
  'avatar' : [] | [UserProfileId],
}
export type UserProfileId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignAdminRole' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'commentPost' : ActorMethod<[bigint, string], Post>,
  'createPost' : ActorMethod<[string, [] | [Blob]], Post>,
  'createStatusUpdate' : ActorMethod<[string], StatusUpdate>,
  'createStory' : ActorMethod<[string], Story>,
  'createUserProfile' : ActorMethod<
    [string, string, string, bigint],
    UserProfile
  >,
  'deleteExpiredStories' : ActorMethod<[], undefined>,
  'deletePostAsAdmin' : ActorMethod<[bigint], undefined>,
  'deleteStatusUpdateAsAdmin' : ActorMethod<[bigint], undefined>,
  'deleteStoryAsAdmin' : ActorMethod<[bigint], undefined>,
  'followUser' : ActorMethod<[UserProfileId], AuthenticatedResponse>,
  'followUserPaid' : ActorMethod<
    [UserProfileId, bigint],
    AuthenticatedResponse
  >,
  'getActiveStories' : ActorMethod<[], Array<Story>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDirectMessagesWith' : ActorMethod<[Principal], Array<DirectMessage>>,
  'getFeedPosts' : ActorMethod<[], Array<Post>>,
  'getMessageThreads' : ActorMethod<[], Array<DirectMessage>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getStatusUpdates' : ActorMethod<[], Array<StatusUpdate>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[bigint], AuthenticatedResponse>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], DirectMessage>,
  'unfollowUser' : ActorMethod<[UserProfileId], AuthenticatedResponse>,
  'updateProfileImage' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];