/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Blob = IDL.Rec();
export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostId = IDL.Nat;
export const Time = IDL.Int;
Blob.fill(IDL.Record({ 'content' : Blob }));
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'commenter' : IDL.Principal,
  'text' : IDL.Text,
  'timestamp' : Time,
});
export const Post = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'image' : IDL.Opt(Blob),
  'comments' : IDL.Vec(Comment),
});
export const StatusUpdateId = IDL.Nat;
export const StatusUpdate = IDL.Record({
  'id' : StatusUpdateId,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const StoryId = IDL.Nat;
export const Story = IDL.Record({
  'id' : StoryId,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const UserProfileId = IDL.Nat;
export const UserProfile = IDL.Record({
  'id' : UserProfileId,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'followers' : IDL.Vec(UserProfileId),
  'following' : IDL.Vec(UserProfileId),
  'followPrice' : IDL.Nat,
  'principalId' : IDL.Principal,
  'avatar' : IDL.Opt(UserProfileId),
});
export const AuthenticatedResponse = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const DirectMessageId = IDL.Nat;
export const DirectMessage = IDL.Record({
  'id' : DirectMessageId,
  'text' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignAdminRole' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'commentPost' : IDL.Func([IDL.Nat, IDL.Text], [Post], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(Blob)], [Post], []),
  'createStatusUpdate' : IDL.Func([IDL.Text], [StatusUpdate], []),
  'createStory' : IDL.Func([IDL.Text], [Story], []),
  'createUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [UserProfile],
      [],
    ),
  'deleteExpiredStories' : IDL.Func([], [], []),
  'deletePostAsAdmin' : IDL.Func([IDL.Nat], [], []),
  'deleteStatusUpdateAsAdmin' : IDL.Func([IDL.Nat], [], []),
  'deleteStoryAsAdmin' : IDL.Func([IDL.Nat], [], []),
  'followUser' : IDL.Func([UserProfileId], [AuthenticatedResponse], []),
  'followUserPaid' : IDL.Func(
      [UserProfileId, IDL.Nat],
      [AuthenticatedResponse],
      [],
    ),
  'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDirectMessagesWith' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getFeedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getMessageThreads' : IDL.Func([], [IDL.Vec(DirectMessage)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getStatusUpdates' : IDL.Func([], [IDL.Vec(StatusUpdate)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Nat], [AuthenticatedResponse], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [DirectMessage], []),
  'unfollowUser' : IDL.Func([UserProfileId], [AuthenticatedResponse], []),
  'updateProfileImage' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Blob = IDL.Rec();
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostId = IDL.Nat;
  const Time = IDL.Int;
  Blob.fill(IDL.Record({ 'content' : Blob }));
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'commenter' : IDL.Principal,
    'text' : IDL.Text,
    'timestamp' : Time,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'image' : IDL.Opt(Blob),
    'comments' : IDL.Vec(Comment),
  });
  const StatusUpdateId = IDL.Nat;
  const StatusUpdate = IDL.Record({
    'id' : StatusUpdateId,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const StoryId = IDL.Nat;
  const Story = IDL.Record({
    'id' : StoryId,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const UserProfileId = IDL.Nat;
  const UserProfile = IDL.Record({
    'id' : UserProfileId,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'followers' : IDL.Vec(UserProfileId),
    'following' : IDL.Vec(UserProfileId),
    'followPrice' : IDL.Nat,
    'principalId' : IDL.Principal,
    'avatar' : IDL.Opt(UserProfileId),
  });
  const AuthenticatedResponse = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const DirectMessageId = IDL.Nat;
  const DirectMessage = IDL.Record({
    'id' : DirectMessageId,
    'text' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignAdminRole' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'commentPost' : IDL.Func([IDL.Nat, IDL.Text], [Post], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(Blob)], [Post], []),
    'createStatusUpdate' : IDL.Func([IDL.Text], [StatusUpdate], []),
    'createStory' : IDL.Func([IDL.Text], [Story], []),
    'createUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [UserProfile],
        [],
      ),
    'deleteExpiredStories' : IDL.Func([], [], []),
    'deletePostAsAdmin' : IDL.Func([IDL.Nat], [], []),
    'deleteStatusUpdateAsAdmin' : IDL.Func([IDL.Nat], [], []),
    'deleteStoryAsAdmin' : IDL.Func([IDL.Nat], [], []),
    'followUser' : IDL.Func([UserProfileId], [AuthenticatedResponse], []),
    'followUserPaid' : IDL.Func(
        [UserProfileId, IDL.Nat],
        [AuthenticatedResponse],
        [],
      ),
    'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDirectMessagesWith' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getFeedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getMessageThreads' : IDL.Func([], [IDL.Vec(DirectMessage)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getStatusUpdates' : IDL.Func([], [IDL.Vec(StatusUpdate)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Nat], [AuthenticatedResponse], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [DirectMessage], []),
    'unfollowUser' : IDL.Func([UserProfileId], [AuthenticatedResponse], []),
    'updateProfileImage' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };